import { test, expect } from '@playwright/test'
import { Buffer } from 'node:buffer'

const assertFits = async locator => {
  const box = await locator.boundingBox()
  const viewport = locator.page().viewportSize()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.y).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(viewport.width + 1)
  expect(box.y + box.height).toBeLessThanOrEqual(viewport.height + 1)
}

const expectTokenColor = async (locator, property, token) => {
  const expected = await locator.evaluate((node, token) => {
    const sample = document.createElement('span')
    sample.style.color = `var(${token})`
    node.append(sample)
    const color = window.getComputedStyle(sample).color
    sample.remove()
    return color
  }, token)
  await expect(locator).toHaveCSS(property, expected)
}

test('Admin 黑色面板与彩色操作层级、主题及动效偏好保持一致', async ({ page }) => {
  await page.goto('/admin/')
  await expect(page.locator('#stat-websites')).not.toHaveText('—')
  await expectTokenColor(page.locator('body'), 'background-color', '--surface-page')
  await expectTokenColor(page.locator('.dashboard-hero'), 'background-color', '--surface-card')
  await expectTokenColor(page.locator('.nav-item.active'), 'color', '--accent')
  await expectTokenColor(page.locator('.content-header .eyebrow'), 'color', '--accent-secondary')
  await expect(page.locator('#page-title')).toHaveCSS('animation-name', 'none')
  await expect(page.locator('#admin-preview')).toHaveAttribute('href', 'http://127.0.0.1:5173/')
  await expect(page.locator('.site-link')).toHaveText('线上站点 ↗')
  await expect(page.locator('.site-link')).not.toHaveAttribute('href', '/')
  await expect(page.locator('.admin-local-label')).toHaveText('LOCAL / 127.0.0.1')
  await page.screenshot({ path: 'e2e/screenshots/admin-black-dashboard.png', fullPage: true })

  const theme = page.getByRole('combobox', { name: '管理页主题' })
  await theme.selectOption('light')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expectTokenColor(page.locator('body'), 'background-color', '--surface-page')
  await page.click('.nav-item[data-view="websites"]')
  await expectTokenColor(page.locator('[data-add-website]'), 'background-color', '--accent')
  await expectTokenColor(page.locator('[data-add-website]'), 'color', '--on-accent')
  await page.screenshot({ path: 'e2e/screenshots/admin-light-list.png', fullPage: true })
  await theme.selectOption('system')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')

  await page.getByRole('button', { name: '关闭管理页动效' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await expect(page.locator('canvas.tech-field')).toHaveCount(0)
  await expect(page.locator('.view.active')).toHaveCSS('animation-name', 'none')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await expect(theme).toHaveValue('system')
  await page.getByRole('button', { name: '开启管理页动效' }).click()
  await expect(page.locator('canvas.tech-field')).toBeVisible()
})

test('Admin 主题在同源标签页同步，窄屏导航关闭后可使用编辑弹窗', async ({ page, context }) => {
  await page.goto('/admin/')
  const other = await context.newPage()
  await other.goto('/admin/')
  await other.locator('#admin-theme').selectOption('light')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await other.close()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('#admin-sidebar')).toHaveAttribute('inert', '')
  await page.locator('#admin-menu').click()
  await expect(page.locator('#admin-menu')).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('#admin-sidebar')).toHaveCSS('transform', 'none')
  await assertFits(page.locator('#admin-sidebar'))
  await expect(page.locator('#locale-select')).toBeVisible()
  await expect(page.locator('.site-link')).toBeVisible()
  await page.screenshot({ path: 'e2e/screenshots/admin-mobile-menu.png' })
  await page.locator('.nav-item[data-view="websites"]').click()
  await expect(page.locator('#admin-menu')).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('#admin-sidebar')).toHaveAttribute('inert', '')
  await expect(page.locator('#page-title')).toBeFocused()
  await page.locator('[data-add-website]').click()
  await assertFits(page.locator('.editor-modal'))
  await expect(page.locator('#nav-form [name="name"]')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.locator('#editor-drawer')).toBeHidden()
  await page.locator('#admin-menu').click()
  await page.keyboard.press('Escape')
  await expect(page.locator('#admin-menu')).toBeFocused()
  await expect(page.locator('#admin-menu-backdrop')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Admin 按钮、操作菜单及弹窗具有交互反馈并尊重减少动效', async ({ page }) => {
  await page.goto('/admin/')
  await page.locator('.nav-item[data-view="websites"]').click()
  const create = page.locator('[data-add-website]')
  await expectTokenColor(create, 'background-color', '--accent')
  await expect(create).toHaveCSS('border-radius', '6px')
  const sheen = () => create.evaluate(node => window.getComputedStyle(node, '::after').transform)
  const initialSheen = await sheen()
  await create.hover()
  await expect.poll(sheen).not.toBe(initialSheen)
  await expect(create).not.toHaveCSS('transform', 'none')
  await create.focus()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  await expect(create).toBeFocused()
  await expect(create).toHaveCSS('outline-style', 'solid')
  await create.click()
  await expect(page.locator('.editor-modal')).toHaveCSS('animation-name', 'admin-dialog-in')
  await page.keyboard.press('Escape')

  const action = page.locator('#navigation .kebab-toggle').first()
  await action.click()
  const menu = page.locator('.kebab-menu:not([hidden])')
  await expect(menu).toHaveCSS('animation-name', 'modal-in')
  const remove = menu.locator('.ui-button-danger')
  await remove.hover()
  await expectTokenColor(remove, 'color', '--danger')
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: '关闭管理页动效' }).click()
  await create.hover()
  await expect(create).toHaveCSS('transform', 'none')
  expect(await create.evaluate(node => window.getComputedStyle(node, '::after').display)).toBe('none')
  await create.click()
  await expect(page.locator('.editor-modal')).toHaveCSS('animation-name', 'none')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '开启管理页动效' }).click()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await create.hover()
  await expect(create).toHaveCSS('transform', 'none')
  expect(await create.evaluate(node => window.getComputedStyle(node, '::after').display)).toBe('none')
})

test('Admin 导入向导在黑色与手机视口可读，模拟分析不写实际工具', async ({ page, request }) => {
  const tools = await (await request.get('/api/tools')).json()
  const tool = tools.find(item => item.runtime === 'static')
  const manifest = { ...tool, id: 'appearance-preview', name: '外观预览', entry: 'index.html', version: '1.0.0', display: { mode: 'embedded', height: 'auto' } }
  await page.route('**/api/**', route => {
    if (route.request().method() === 'GET') return route.continue()
    if (route.request().url().endsWith('/tools/analyze')) return route.fulfill({ json: {
      token: 'appearance-preview', kind: 'html', format: 'single-html', runtime: 'static', entry: 'index.html', files: ['index.html'],
      stats: { totalBytes: 100, zipBytes: 100 }, suggested: { id: manifest.id, name: manifest.name }, manifestDraft: manifest,
      compat: [], notes: [], previewUrl: '/__tool_preview/appearance-preview/index.html',
    } })
    if (route.request().url().includes('/tools/staging/')) return route.fulfill({ json: { ok: true } })
    return route.abort()
  })
  await page.route('**/__tool_preview/appearance-preview/**', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><html><body style="background:#111;color:#eee"><h1>Preview</h1></body></html>' }))
  await page.goto('/admin/')
  await page.locator('.nav-item[data-view="import"]').click()
  await page.locator('#tool-file-input').setInputFiles({ name: 'preview.html', mimeType: 'text/html', buffer: Buffer.from('<h1>Preview</h1>') })
  const dialog = page.getByRole('dialog', { name: '导入向导' })
  await expect(dialog).toBeVisible()
  await expect(page.locator('.wizard-summary')).toBeVisible()
  for (let step = 2; step <= 5; step += 1) {
    await page.locator('#wizard-next').click()
    await expect(page.locator(`#wizard-steps [data-step="${step}"]`)).toHaveClass(/active/)
  }
  await expect(page.locator('.wizard-preview-frame iframe')).toBeVisible()
  await page.screenshot({ path: 'e2e/screenshots/admin-black-import.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await assertFits(dialog)
  await assertFits(page.locator('#wizard-next'))
  await assertFits(page.locator('#wizard-close'))
  await expect(page.locator('.wizard-preview-bar select')).toHaveCSS('min-width', '140px')
  for (const button of await page.locator('.wizard-preview-bar button').all()) await assertFits(button)
  await page.screenshot({ path: 'e2e/screenshots/admin-mobile-import.png' })
  await page.locator('#wizard-close').click()
  await expect(dialog).toBeHidden()
})
