import { test, expect } from '@playwright/test'
import { Buffer } from 'node:buffer'
import { randomUUID } from 'node:crypto'
import { readFile, writeFile, rm } from 'node:fs/promises'
import { resolve } from 'node:path'

const indexPath = resolve('src/data/cfgs.json')
const cfgDirectory = resolve('public/cfgs')

test('Admin 上传、替换、历史预览与回滚 CFG，原文下载保留 BOM 与换行，删除经过确认', async ({ page, request }) => {
  const originalIndex = await readFile(indexPath)
  const baseline = JSON.parse(originalIndex.toString('utf8'))
  const baselineIds = new Set(baseline.map(item => item.id))
  const fixtureName = `CFG 管理测试 ${randomUUID()}`
  const originalContent = '\uFEFF// CFG fixture\r\nbind "w" "+forward"\r\nbind x say \u0006社区\u0007ffffff彩字\u000b保留\u000e原文\u0010\r\n'
  const replacedContent = '// replacement\nvolume "0.4"\n'
  let visitor
  try {
    await page.goto('/admin/#cfgs')
    await expect(page.locator('#page-title')).toHaveText('CFG 配置库')
    await page.getByRole('button', { name: '上传 CFG', exact: true }).click()
    const editor = page.getByRole('dialog', { name: '上传 CFG 配置' })
    await expect(editor).toBeVisible()
    await expect(page.locator('#cfg-form [name="name"]')).toBeFocused()
    await page.locator('#cfg-file').setInputFiles({ name: 'fixture-autoexec.cfg', mimeType: 'text/plain', buffer: Buffer.from(originalContent) })
    await expect(page.locator('#cfg-file-status')).toContainText('原始 BOM 与换行符均保留')
    await expect(page.locator('#cfg-file-status')).toContainText('彩色字体控制符原样保留')
    expect(await page.locator('#cfg-content-preview').textContent()).toBe(originalContent)
    await page.locator('#cfg-form [name="name"]').fill(fixtureName)
    await page.locator('#cfg-form [name="description"]').fill('用于验证公开 CFG 文件库。\n保留多行说明。')
    await page.locator('#cfg-form [name="changelog"]').fill('初始绑定版本')
    await page.locator('#cfg-form [name="tags"]').fill('测试, CS2')
    const created = page.waitForResponse(response => response.url().endsWith('/api/cfgs') && response.request().method() === 'POST')
    await page.locator('#cfg-save').click()
    const response = await created
    expect(response.status()).toBe(201)
    const item = await response.json()
    expect(item.version).toBe(1)
    const card = page.locator(`[data-cfg-id="${item.id}"]`)
    await expect(card).toBeVisible()
    expect(await readFile(resolve(cfgDirectory, `${item.id}.cfg`))).toEqual(Buffer.from(originalContent))
    expect((await (await request.get(`/api/cfgs/${item.id}`)).json()).version).toBe(1)
    visitor = await page.context().newPage()
    await visitor.goto(`http://127.0.0.1:5173/#/cfg/${item.id}`)
    await expect(visitor.getByRole('heading', { name: fixtureName, exact: true })).toBeVisible()
    await expect(visitor.locator('.cfg-library-code')).toContainText('+forward')
    expect(await visitor.locator('.cfg-library-code code').textContent()).toBe(originalContent)
    await expect(page.locator('#stat-tools')).not.toHaveText('—')
    await page.screenshot({ path: 'e2e/screenshots/admin-cfg-library-desktop.png', fullPage: true })

    await card.getByRole('button', { name: '预览', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '预览 CFG 配置' })).toBeVisible()
    await expect(page.locator('#cfg-content-preview')).toContainText('bind "w" "+forward"')
    await expect(page.locator('#cfg-form [name="name"]')).toHaveAttribute('readonly', '')
    await expect(page.locator('#cfg-form .admin-draft')).toHaveCount(0)
    await expect(page.locator('#cfg-save')).toBeHidden()
    const downloadPending = page.waitForEvent('download')
    await page.locator('#cfg-download').click()
    const download = await downloadPending
    expect(download.suggestedFilename()).toBe('fixture-autoexec.cfg')
    expect(await readFile(await download.path())).toEqual(Buffer.from(originalContent))
    await page.locator('#cfg-cancel').click()
    await expect(card.getByRole('button', { name: '预览', exact: true })).toBeFocused()

    await card.getByRole('button', { name: '编辑', exact: true }).click()
    await expect(page.locator('#cfg-save')).toBeEnabled()
    await page.locator('#cfg-form [name="description"]').fill('仅修改说明，保留原始字节。')
    const metadataRequest = page.waitForRequest(value => value.url().endsWith(`/api/cfgs/${item.id}`) && value.method() === 'PUT')
    await page.locator('#cfg-save').click()
    expect((await metadataRequest).postDataJSON()).not.toHaveProperty('content')
    await expect(card).toContainText('仅修改说明，保留原始字节。')
    expect(await readFile(resolve(cfgDirectory, `${item.id}.cfg`))).toEqual(Buffer.from(originalContent))

    await page.setViewportSize({ width: 390, height: 844 })
    await card.getByRole('button', { name: '编辑', exact: true }).click()
    await expect(page.locator('#cfg-save')).toBeEnabled()
    await page.locator('#cfg-file').setInputFiles({ name: 'fixture-replaced.cfg', mimeType: 'text/plain', buffer: Buffer.from(replacedContent) })
    await page.locator('#cfg-form [name="changelog"]').fill('第二版调整音量')
    await expect(page.locator('#cfg-content-preview')).toContainText('volume "0.4"')
    await expect(page.locator('.editor-modal')).toHaveCSS('opacity', '1')
    await expect(page.locator('#toasts .toast')).toHaveCount(0)
    await page.screenshot({ path: 'e2e/screenshots/admin-cfg-library-mobile.png' })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.locator('#cfg-save').click()
    await expect(card).toContainText('fixture-replaced.cfg')
    await expect(card).toContainText('v2')
    expect(await readFile(resolve(cfgDirectory, `${item.id}.cfg`))).toEqual(Buffer.from(replacedContent))
    const published = await request.get(`/cfgs/${item.id}.cfg`)
    expect(published.ok()).toBe(true)
    expect(await published.body()).toEqual(Buffer.from(replacedContent))
    await visitor.reload()
    await expect(visitor.locator('.cfg-library-code')).toContainText('volume "0.4"')
    await expect(visitor.locator('.cfg-library-preview-bar')).toContainText('fixture-replaced.cfg')
    await page.locator('#cfg-query').fill('not-a-matching-cfg')
    await expect(card).toHaveCount(0)
    await page.locator('#cfg-query').fill(fixtureName)
    await expect(card).toBeVisible()

    const v2 = await (await request.get(`/api/cfgs/${item.id}`)).json()
    expect(v2.history).toHaveLength(1)
    const v1 = v2.history[0]
    expect(v1).toMatchObject({ version: 1, filename: 'fixture-autoexec.cfg', changelog: '初始绑定版本' })
    const historicAsset = await request.get(`/cfgs/${item.id}.${v1.id}.cfg`)
    expect(historicAsset.status()).toBe(200)
    expect(await historicAsset.body()).toEqual(Buffer.from(originalContent))
    await card.getByRole('button', { name: '预览', exact: true }).click()
    await page.getByRole('combobox', { name: '历史 CFG 版本', exact: true }).selectOption(v1.id)
    await expect(page.locator('#cfg-history-preview')).toContainText('+forward')
    await expect(page.locator('#cfg-form .admin-draft')).toHaveCount(0)
    await expect(page.getByRole('button', { name: '回滚为新版本', exact: true })).toBeHidden()
    const historicDownloadPending = page.waitForEvent('download')
    await page.getByRole('button', { name: '下载历史 CFG', exact: true }).click()
    const historicDownload = await historicDownloadPending
    expect(historicDownload.suggestedFilename()).toBe('fixture-autoexec.cfg')
    expect(await readFile(await historicDownload.path())).toEqual(Buffer.from(originalContent))
    await page.locator('#cfg-cancel').click()
    await expect(page.locator('#cfg-form')).toBeHidden()

    await card.getByRole('button', { name: '编辑', exact: true }).click()
    await expect(page.locator('#cfg-save')).toBeEnabled()
    await page.getByRole('combobox', { name: '历史 CFG 版本', exact: true }).selectOption(v1.id)
    await page.getByRole('button', { name: '回滚为新版本', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '回滚 CFG 版本', exact: true })).toBeVisible()
    const rolledResponse = page.waitForResponse(value => value.url().endsWith(`/api/cfgs/${item.id}/rollback`) && value.request().method() === 'POST')
    await page.getByRole('button', { name: '确认回滚', exact: true }).click()
    expect((await rolledResponse).ok()).toBe(true)
    await expect(card).toContainText('v3')
    await expect(card).toContainText('fixture-autoexec.cfg')
    const v3 = await (await request.get(`/api/cfgs/${item.id}`)).json()
    expect(v3.history.map(old => old.version)).toEqual([2, 1])
    expect(v3.changelog).toBe('回滚至 v1')
    expect(await readFile(resolve(cfgDirectory, `${item.id}.cfg`))).toEqual(Buffer.from(originalContent))
    await visitor.reload()
    await expect(visitor.locator('.cfg-library-code')).toContainText('+forward')
    await expect(visitor.locator('.cfg-library-preview-bar')).toContainText('v3')

    await card.getByRole('button', { name: '删除', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '删除 CFG 配置' })).toBeVisible()
    await expect(page.locator('#modal-cancel')).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(page.locator('#modal-ok')).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(card).toBeVisible()
    await expect(card.getByRole('button', { name: '删除', exact: true })).toBeFocused()
    await card.getByRole('button', { name: '删除', exact: true }).click()
    await page.locator('#modal-ok').click()
    await expect(card).toHaveCount(0)
    expect((await request.get(`/api/cfgs/${item.id}`)).status()).toBe(404)
    for (const old of v3.history) expect((await request.get(`/cfgs/${item.id}.${old.id}.cfg`)).status()).toBe(404)
    await visitor.reload()
    await expect(visitor.getByRole('heading', { name: '这份 CFG 已移除或不存在' })).toBeVisible()
  } finally {
    await visitor?.close()
    // Only remove this run's UUID-named fixture; retain any unrelated concurrent edits.
    const current = JSON.parse(await readFile(indexPath, 'utf8'))
    const fixtures = current.filter(item => item.name === fixtureName && !baselineIds.has(item.id))
    for (const item of fixtures) {
      await rm(resolve(cfgDirectory, `${item.id}.cfg`), { force: true })
      for (const old of item.history || []) await rm(resolve(cfgDirectory, `${item.id}.${old.id}.cfg`), { force: true })
    }
    const remaining = current.filter(item => !fixtures.some(fixture => fixture.id === item.id))
    await writeFile(indexPath, JSON.stringify(remaining) === JSON.stringify(baseline) ? originalIndex : `${JSON.stringify(remaining, null, 2)}\n`)
  }
})

test('CFG 上传校验和保存失败保留当前表单，不创建项目文件', async ({ page }) => {
  await page.goto('/admin/#cfgs')
  await page.getByRole('button', { name: '上传 CFG', exact: true }).click()
  await page.locator('#cfg-file').setInputFiles({ name: 'invalid.cfg', mimeType: 'text/plain', buffer: Buffer.from([0xff, 0xfe, 0x61]) })
  await expect(page.locator('#cfg-form-error')).toContainText('UTF-8')
  await expect(page.locator('#cfg-save')).toBeDisabled()
  await page.locator('#cfg-file').setInputFiles({ name: 'too-large.cfg', mimeType: 'text/plain', buffer: Buffer.alloc(256 * 1024 + 1, 'a') })
  await expect(page.locator('#cfg-form-error')).toContainText('256 KiB')
  await page.locator('#cfg-file').setInputFiles({ name: 'binary.cfg', mimeType: 'text/plain', buffer: Buffer.from('echo\u0000binary') })
  await expect(page.locator('#cfg-form-error')).toContainText('不支持的控制字符')
  await expect(page.locator('#cfg-save')).toBeDisabled()
  await page.locator('#cfg-file').setInputFiles({ name: 'unsaved.cfg', mimeType: 'text/plain', buffer: Buffer.from('volume "0.5"\r\n') })
  await expect(page.locator('#cfg-save')).toBeEnabled()
  await page.route('**/api/cfgs', route => route.request().method() === 'POST' ? route.fulfill({ status: 500, json: { error: '模拟写入失败' } }) : route.continue())
  await page.locator('#cfg-save').click()
  await expect(page.locator('#cfg-form-error')).toHaveText('模拟写入失败')
  await expect(page.locator('#cfg-form [name="filename"]')).toHaveValue('unsaved.cfg')
  await expect(page.locator('#cfg-content-preview')).toContainText('volume "0.5"')
  await expect(page.locator('#cfg-save')).toBeEnabled()
})
