import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { normalizeManifest, validateManifest, suggestPermissionsFromHtml } from '../scripts/tool-manifest.mjs'

const entry = new URL('../templates/tool/index.html', import.meta.url)
const html = await readFile(entry, 'utf8')
const manifest = JSON.parse(await readFile(new URL('../templates/tool/manifest.json', import.meta.url), 'utf8'))
const sample = '  中文 🎮 <script>示例</script>\n保留空格  '

test('单文件模板可离线打开：处理、复制降级、下载、主题和手机布局', async ({ page }, testInfo) => {
  const errors = []
  const requests = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto(entry.href)
  await expect(page.getByRole('button', { name: '复制结果' })).toBeDisabled()
  await page.getByRole('button', { name: '开始处理' }).click()
  await expect(page.getByRole('status')).toHaveText('请先输入内容。')
  await page.getByLabel('输入内容').fill(sample)
  await page.getByRole('button', { name: '开始处理' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('处理结果')).toHaveValue(sample)
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', {
    value: { writeText: () => Promise.reject(new Error('permission denied')) }, configurable: true,
  }))
  await page.getByRole('button', { name: '复制结果' }).click()
  await expect(page.getByRole('status')).toContainText('手动复制')
  expect(await page.getByLabel('处理结果').evaluate(element => element.value.slice(element.selectionStart, element.selectionEnd))).toBe(sample)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载结果' }).click()
  const file = await downloaded
  expect(file.suggestedFilename()).toBe('result.txt')
  expect(await readFile(await file.path(), 'utf8')).toBe(sample)
  await page.getByLabel('输入内容').fill('')
  await page.getByRole('button', { name: '开始处理' }).click()
  await expect(page.getByRole('status')).toContainText('已保留上次结果')
  await expect(page.getByLabel('处理结果')).toHaveValue(sample)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await expect(page.getByRole('button', { name: '开始处理' })).toHaveCSS('transition-duration', '0s')
  await page.screenshot({ path: testInfo.outputPath('standalone-mobile.png'), fullPage: true })
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: '清空', exact: true }).click()
  await expect(page.getByLabel('输入内容')).toBeFocused()
  await expect(page.getByLabel('处理结果')).toHaveValue('')
  await expect(page.getByRole('button', { name: '下载结果' })).toBeDisabled()
  expect(requests.filter(url => /^https?:/.test(url))).toEqual([])
  expect(errors).toEqual([])
})

test('模板接入真实工具宿主：权限、透明主题、复制与高度回缩', async ({ page, context }, testInfo) => {
  expect(validateManifest(manifest, { upload: true, hasEntry: true })).toEqual([])
  const suggested = suggestPermissionsFromHtml(html, ['index.html'])
  expect(suggested.clipboard).toBe(true)
  expect(suggested.download).toBe(true)
  expect(suggested.sameOrigin).toBe(false)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  // Chromium 对沙箱的 opaque origin 访问本地开发 SDK 要求本地网络权限。
  await context.grantPermissions(['clipboard-read', 'clipboard-write', 'local-network-access'])
  await page.route('**/tools-manifests.json', route => route.fulfill({ json: [normalizeManifest(manifest, 10)] }))
  await page.route('**/tools/my-tool/index.html', route => route.fulfill({ contentType: 'text/html', body: html }))
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto('/#/tools/my-tool')
  const iframe = page.getByTestId('tool-frame')
  const frame = page.frameLocator('[data-testid="tool-frame"]')
  await expect(iframe).toHaveAttribute('sandbox', 'allow-scripts allow-downloads allow-forms')
  await expect(frame.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(frame.locator('body')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  const hostAccent = () => page.locator('html').evaluate(element => window.getComputedStyle(element).getPropertyValue('--accent').trim())
  const frameAccent = () => frame.locator('html').evaluate(element => element.style.getPropertyValue('--accent').trim())
  await expect.poll(frameAccent).toBe(await hostAccent())
  await frame.getByLabel('输入内容').fill(sample)
  await frame.getByRole('button', { name: '开始处理' }).click()
  await frame.getByRole('button', { name: '复制结果' }).click()
  await expect(frame.getByRole('status')).toHaveText('已复制。')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(sample)
  await page.screenshot({ path: testInfo.outputPath('embedded-dark.png'), fullPage: true })
  await page.getByLabel('选择主题').selectOption('light')
  await expect(frame.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect.poll(frameAccent).toBe(await hostAccent())
  await expect(frame.locator('body')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await frame.getByLabel('输入内容').evaluate(element => { element.style.height = '850px' })
  await expect.poll(async () => (await iframe.boundingBox()).height).toBeGreaterThan(850)
  await frame.getByLabel('输入内容').evaluate(element => { element.style.height = '' })
  await expect.poll(async () => (await iframe.boundingBox()).height).toBeLessThan(850)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  expect(await frame.locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('embedded-light-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('SDK 无法加载时仍能处理，复制失败保留内容', async ({ page }) => {
  await page.route('**/tools-manifests.json', route => route.fulfill({ json: [normalizeManifest(manifest, 10)] }))
  await page.route('**/tools/my-tool/index.html', route => route.fulfill({ contentType: 'text/html', body: html }))
  await page.route('**/toolbox-bridge.js', route => route.abort())
  await page.goto('/#/tools/my-tool')
  const frame = page.frameLocator('[data-testid="tool-frame"]')
  await expect(frame.getByRole('status')).toContainText('主题连接不可用')
  await frame.getByLabel('输入内容').fill(sample)
  await frame.getByRole('button', { name: '开始处理' }).click()
  await frame.getByRole('button', { name: '复制结果' }).click()
  await expect(frame.getByRole('status')).toContainText('手动复制')
  await expect(frame.getByLabel('处理结果')).toHaveValue(sample)
})

test('处理失败后仍可复制保留结果，旧复制请求不会覆盖错误提示', async ({ page }) => {
  await page.goto(entry.href)
  await page.getByLabel('输入内容').fill(sample)
  await page.getByRole('button', { name: '开始处理' }).click()
  await page.getByLabel('输入内容').fill('')
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', {
    configurable: true,
    value: { writeText: () => new Promise(resolve => { window.finishCopy = resolve }) },
  }))
  const copy = page.getByRole('button', { name: '复制结果' })
  await copy.click()
  await expect(copy).toBeDisabled()
  await page.getByRole('button', { name: '开始处理' }).click()
  await expect(page.getByRole('status')).toContainText('已保留上次结果')
  await expect(copy).toBeEnabled()
  await page.evaluate(() => window.finishCopy())
  await expect(page.getByRole('status')).toContainText('已保留上次结果')
  await expect(page.getByLabel('处理结果')).toHaveValue(sample)
})
