import { test, expect } from '@playwright/test'

test('工具行保持紧凑，键盘收藏和手机打开入口可用', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.getByTestId('boot-layer')).toBeHidden()
  const card = page.locator('#today .tool-card').first()
  await expect(card).toBeVisible()
  await card.scrollIntoViewIfNeeded()
  const open = card.locator('.tool-open')
  const row = await card.boundingBox()
  const action = await open.boundingBox()
  expect(row.height).toBeLessThanOrEqual(110)
  expect(action.width).toBeLessThan(80)
  expect(action.x).toBeGreaterThan((await card.locator('.tool-card-copy').boundingBox()).x)
  expect(Math.abs(action.y + action.height / 2 - row.y - row.height / 2)).toBeLessThan(3)
  const link = card.locator('.tool-card-link')
  await link.focus()
  await expect(link).toHaveCSS('outline-style', 'solid')
  const favorite = card.locator('.favorite-button')
  const oldState = await favorite.getAttribute('aria-pressed')
  await favorite.focus()
  await page.keyboard.press('Space')
  await expect(favorite).toHaveAttribute('aria-pressed', oldState === 'true' ? 'false' : 'true')
  await expect(page).toHaveURL(/#\/$/)
  await expect(favorite.locator('svg')).toHaveAttribute('fill', oldState === 'true' ? 'none' : 'currentColor')

  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(async () => (await card.boundingBox()).height).toBeLessThanOrEqual(110)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  expect((await favorite.boundingBox()).width).toBeGreaterThanOrEqual(40)
  const target = await link.getAttribute('href')
  await open.click()
  await expect(page).toHaveURL(new RegExp(target.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$'))

  await page.goto('/#/tools')
  await expect(page.locator('.directory .tool-card').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  expect((await page.locator('.directory .tool-card').first().boundingBox()).height).toBeLessThanOrEqual(110)
  const longCopy = page.getByRole('link', { name: '打开 Agent Development Control Plane', exact: true }).locator('.tool-card-copy')
  const copyBox = await longCopy.boundingBox()
  const descriptionBox = await longCopy.locator('small').boundingBox()
  expect(descriptionBox.x).toBeGreaterThanOrEqual(copyBox.x)
  expect(descriptionBox.x + descriptionBox.width).toBeLessThanOrEqual(copyBox.x + copyBox.width + 1)
  await expect(longCopy.locator('small')).toHaveCSS('text-overflow', 'ellipsis')
})

test('停用工具禁止打开和收藏，减少动效时箭头保持静止', async ({ page }) => {
  await page.route('**/tools-manifests.json', async route => {
    const response = await route.fetch()
    const tools = await response.json()
    await route.fulfill({ response, json: tools.map(tool => tool.id === 'json' ? { ...tool, status: 'disabled' } : tool) })
  })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/tools')
  await expect(page.getByTestId('boot-layer')).toBeHidden()
  const unavailable = page.getByRole('link', { name: '暂不可用 JSON 格式化' })
  await expect(unavailable).toHaveAttribute('aria-disabled', 'true')
  await expect(unavailable).toHaveAttribute('tabindex', '-1')
  await expect(page.locator('.tool-card').filter({ has: unavailable }).getByRole('button')).toBeDisabled()
  // Native links need an explicit navigation guard in addition to aria-disabled.
  await unavailable.dispatchEvent('click')
  await expect(page).toHaveURL(/#\/tools$/)
  const available = page.getByRole('link', { name: '打开 Base64', exact: true })
  await available.hover()
  await expect(available.locator('.card-arrow')).toHaveCSS('transform', 'none')
})
