import { test, expect } from '@playwright/test'

test.use({ reducedMotion: 'reduce' })
const resource = { id: 'review-prompt', name: '同名审查资源', kind: 'prompt', description: '审查目标代码', install: '', content: 'Review {{code}}', url: '', tags: ['代码'], enabled: true, updated: '2026-09-08', order: 10 }
const agent = { ...resource, id: 'review-agent', kind: 'agent', description: 'agent-unique-marker', content: '审查代理配置', order: 20 }
const workflow = { id: 'review-flow', name: '审查流程', category: 'code-review', description: '按步骤审查代码', tags: ['代码'], enabled: true, updated: '2026-09-08', order: 1, steps: [{ title: '审查变更', description: '打开关联提示词', resourceId: resource.id }] }
async function mockData(context, name, value) {
  await context.route(`**/src/data/${name}.json*`, route => route.fulfill({ contentType: 'text/javascript', body: `export default ${JSON.stringify(value)}` }))
}
test.beforeEach(async ({ context, page }) => {
  await page.addInitScript(() => localStorage.setItem('devos-motion', 'off'))
  await mockData(context, 'ai-resources', [resource, agent, { ...resource, id: 'private-prompt', name: '未发布提示词', enabled: false }])
  await mockData(context, 'ai-workflows', [workflow])
  await mockData(context, 'categories', [{ id: 'dev', name: '开发', icon: 'Code2', order: 20 }, { id: 'ops', name: '运维', icon: 'Server', order: 0 }])
  await mockData(context, 'navigation', [
    { id: 'docs', name: '开发文档', category: 'dev', url: 'https://docs.example.com', description: '代码接口说明', tags: ['文档'], icon: 'letter', enabled: true, order: 1 },
    { id: 'logs', name: '日志看板', category: 'ops', url: 'https://logs.example.com', description: '社区服日志检索', tags: ['CS2', '排障'], icon: 'letter', enabled: true, order: 1 },
    { id: 'metrics', name: '服务监控', category: 'ops', url: 'https://metrics.example.com', description: '服务器指标', tags: ['监控'], icon: 'letter', enabled: true, order: 2 },
    { id: 'hidden', name: '未公开入口', category: 'ops', url: 'https://hidden.example.com', description: '', tags: ['隐藏标签'], icon: 'letter', enabled: false, order: 3 },
  ])
})

test('网站导航搜索域名、分类和标签可组合，刷新保留并支持清除', async ({ page }) => {
  await page.goto('/#/nav')
  await expect(page.locator('.category h3').first()).toHaveText('运维')
  await expect(page.locator('.nav-card')).toHaveCount(3)
  await expect(page.getByLabel('网站标签').locator('option', { hasText: '隐藏标签' })).toHaveCount(0)
  await page.getByLabel('网站分类', { exact: true }).selectOption('ops')
  await page.getByLabel('网站标签', { exact: true }).selectOption('CS2')
  await page.getByLabel('搜索网站', { exact: true }).fill('LOGS.EXAMPLE')
  await expect(page.locator('.nav-card')).toHaveCount(1)
  await expect(page.locator('.nav-card')).toContainText('日志看板')
  await expect(page.locator('.content-count[role="status"]')).toHaveText('1 个网站 · 1 个分类')
  await page.reload()
  await expect(page.getByLabel('网站分类', { exact: true })).toHaveValue('ops')
  await expect(page.getByLabel('网站标签', { exact: true })).toHaveValue('CS2')
  await expect(page.getByLabel('搜索网站', { exact: true })).toHaveValue('LOGS.EXAMPLE')
  await page.getByLabel('搜索网站', { exact: true }).fill('不存在的入口')
  await expect(page.getByRole('heading', { name: '没有匹配的网站' })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选', exact: true }).click()
  await expect(page).toHaveURL(/#\/nav$/)
  await expect(page.locator('.nav-card')).toHaveCount(3)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByLabel('网站标签', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('AI 类型与关键词组合不重置，详情刷新与分享定位同一条资源', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/#/ai')
  await page.getByRole('tab', { name: 'Prompts', exact: true }).click()
  await page.getByLabel('搜索 AI 资源', { exact: true }).fill('审查')
  await expect(page.getByRole('tab', { name: 'Prompts', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.ai-resource-card')).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('tab', { name: 'Prompts', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('搜索 AI 资源', { exact: true })).toHaveValue('审查')
  await page.locator('.ai-resource-card').press('Enter')
  await expect(page).toHaveURL(/resource=review-prompt/)
  await page.reload()
  const dialog = page.getByRole('dialog', { name: resource.name, exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('textbox', { name: 'code', exact: true }).fill('私人测试输入，不能出现在分享链接中')
  await dialog.getByRole('button', { name: '复制页面链接', exact: true }).click()
  const copied = await page.evaluate(() => navigator.clipboard.readText())
  expect(new URL(copied).hash).toBe('#/ai?resource=review-prompt')
  const receiver = await context.newPage()
  await receiver.goto(copied)
  await expect(receiver.getByRole('dialog', { name: resource.name, exact: true })).toBeVisible()
  await expect(receiver.getByRole('textbox', { name: 'code', exact: true })).toHaveValue('')
  await receiver.close()
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('搜索 AI 资源', { exact: true })).toHaveValue('审查')
  await expect(page.getByRole('tab', { name: 'Prompts', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.locator('.ai-resource-card').click()
  await page.goBack()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Prompts', exact: true })).toHaveAttribute('aria-selected', 'true')
})

test('命令面板与首页按资源 ID 直达，同名条目不混淆，失效链接可返回', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.locator('.resource-row[href="#/ai?resource=review-prompt"]')).toHaveCount(1)
  await page.getByRole('button', { name: '打开命令面板', exact: true }).first().click()
  await page.getByRole('combobox', { name: '命令面板搜索' }).fill('agent-unique-marker')
  await page.getByRole('option', { name: new RegExp(resource.name) }).click()
  await expect(page).toHaveURL(/#\/ai\?resource=review-agent$/)
  await expect(page.getByRole('dialog', { name: resource.name, exact: true })).toContainText(agent.content)
  await expect(page.getByRole('dialog', { name: '命令面板' })).toHaveCount(0)
  await page.goto('/#/ai?resource=private-prompt')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('alert')).toContainText('已移除或不存在')
  await page.getByRole('button', { name: '返回列表', exact: true }).click()
  await expect(page).toHaveURL(/#\/ai$/)
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('工作流深链接保留分类，可查看关联资源并返回流程', async ({ page }) => {
  await page.goto('/#/ai?view=workflows&category=code-review&workflow=review-flow')
  const flow = page.getByRole('dialog', { name: workflow.name, exact: true })
  await expect(flow).toBeVisible()
  await flow.getByRole('button', { name: `关联资源：${resource.name}`, exact: true }).click()
  const detail = page.getByRole('dialog', { name: resource.name, exact: true })
  await expect(detail).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await page.reload()
  await expect(detail).toBeVisible()
  await detail.getByRole('button', { name: `返回工作流：${workflow.name}`, exact: true }).click()
  await expect(flow).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(flow.getByRole('link', { name: '从此工作流创建任务包' })).toHaveAttribute('href', '#/tools/ai-context?workflow=review-flow')
  await flow.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.locator('.ai-workflow-filter select')).toHaveValue('code-review')
  await page.getByLabel('搜索 AI 资源', { exact: true }).fill('无匹配')
  await page.getByRole('button', { name: '清除筛选', exact: true }).click()
  await expect(page.locator('.ai-workflow-card')).toHaveCount(1)
})
