import { test, expect } from '@playwright/test'

test.use({ reducedMotion: 'reduce' })
test.beforeEach(async ({ context }) => {
  await context.addInitScript(() => sessionStorage.setItem('devos-boot', '1'))
  const notes = Array.from({ length: 28 }, (_, i) => ({ id: `runbook-${i}`, title: `运维手册 ${i}`, summary: '服务异常排查和恢复步骤', body: `# 运维手册 ${i}\n\n保持配置与日志。`, tags: ['运维'], kind: 'incident', cfgIds: [], projectId: '', enabled: true, order: i, updated: '2026-09-08' }))
  await context.route('**/src/data/notes.json*', route => route.fulfill({ contentType: 'text/javascript', body: `export default ${JSON.stringify(notes)}` }))
})

test('键盘跳过导航、页面切换和命令面板跳转都有内容焦点', async ({ page }) => {
  await page.goto('/#/nav')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: '跳到主要内容' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
  await expect(page).toHaveURL(/#\/nav$/)
  const nav = page.getByRole('navigation', { name: '主导航' })
  await nav.getByRole('link', { name: '笔记', exact: true }).press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
  await expect(nav.getByRole('link', { name: '笔记', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('button', { name: '打开命令面板', exact: true }).click()
  await page.getByRole('combobox', { name: '命令面板搜索' }).fill('运维手册 17')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/notes\/runbook-17$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('#main-content')).toBeFocused()
})

test('长列表返回和浏览器后退恢复位置，搜索输入保持焦点', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/notes')
  const search = page.getByLabel('搜索笔记')
  await search.fill('运维')
  await expect(search).toBeFocused()
  const card = page.locator('.note-card').filter({ hasText: '运维手册 20' })
  await card.scrollIntoViewIfNeeded()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(1000)
  const top = await page.evaluate(() => window.scrollY)
  await card.press('Enter')
  await expect(page).toHaveURL(/#\/notes\/runbook-20/)
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await page.getByRole('link', { name: '← 全部笔记', exact: true }).click()
  await expect(search).toHaveValue('运维')
  await expect.poll(async () => Math.abs(await page.evaluate(() => window.scrollY) - top)).toBeLessThan(4)
  await card.press('Enter')
  await expect(page).toHaveURL(/#\/notes\/runbook-20/)
  await page.goBack()
  await expect(search).toHaveValue('运维')
  await expect.poll(async () => Math.abs(await page.evaluate(() => window.scrollY) - top)).toBeLessThan(4)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('主题和动效偏好实时同步到已打开的页面', async ({ page, context }) => {
  await page.goto('/#/nav')
  const other = await context.newPage()
  await other.goto('/#/library')
  await page.getByLabel('选择主题').selectOption('light')
  await expect(other.getByLabel('选择主题')).toHaveValue('light')
  await expect(other.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: '关闭动效', exact: true }).click()
  await expect(other.locator('html')).toHaveAttribute('data-motion', 'off')
  await other.getByRole('button', { name: '开启动效', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'on')
  await other.getByLabel('选择主题').selectOption('dark')
  await expect(page.getByLabel('选择主题')).toHaveValue('dark')
  await other.close()
})
