import { test, expect } from '@playwright/test'

// Playwright creates a fresh, disposable browser context for every test.
test.use({ reducedMotion: 'reduce' })

async function openWorkspace(page) {
  await page.goto('/#/')
  await expect(page.getByTestId('boot-layer')).toBeHidden()
  await page.getByRole('button', { name: '我的工作区', exact: true }).click()
  await expect(page.getByRole('heading', { name: '今日待办', exact: true })).toBeVisible()
}

test('待办增删、完成状态与便笺在刷新和路由返回后保留', async ({ page }) => {
  await openWorkspace(page)
  const workspace = page.locator('.workspace-panel')
  await expect(workspace.getByRole('checkbox')).toHaveCount(0)
  await expect(workspace.getByRole('button', { name: '添加待办' })).toBeDisabled()
  await workspace.getByRole('textbox', { name: '新增待办' }).fill('  验证浏览器持久化  ')
  await workspace.getByRole('button', { name: '添加待办' }).click()
  await workspace.getByRole('checkbox', { name: '验证浏览器持久化' }).check()
  await workspace.getByRole('textbox', { name: '临时便笺内容' }).fill('第一行灵感\n第二行待整理')
  await expect(workspace.locator('#workspace-note-status')).toHaveText('已自动保存到此浏览器')

  await page.reload()
  await expect(workspace.getByRole('checkbox', { name: '验证浏览器持久化' })).toBeChecked()
  await expect(workspace.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('第一行灵感\n第二行待整理')
  const navigation = page.getByRole('navigation', { name: '主导航' })
  await navigation.getByRole('link', { name: '工具', exact: true }).click()
  await expect(workspace).toHaveCount(0)
  await navigation.getByRole('link', { name: '首页', exact: true }).click()
  await expect(workspace.getByRole('checkbox', { name: '验证浏览器持久化' })).toBeChecked()
  await workspace.getByRole('button', { name: '删除待办：验证浏览器持久化', exact: true }).click()
  await page.reload()
  await expect(workspace.getByRole('checkbox')).toHaveCount(0)
  await expect(workspace.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('第一行灵感\n第二行待整理')
})

test('专注按真实截止时间推进，暂停、刷新、路由返回和重置保持一致', async ({ page }) => {
  const start = Date.parse('2026-09-05T08:00:00Z')
  await page.clock.setFixedTime(start)
  await openWorkspace(page)
  const focus = page.getByRole('region', { name: '专注计时', exact: true })
  const clock = focus.getByRole('timer')
  await focus.getByRole('combobox', { name: '专注时长' }).selectOption('45')
  await expect(clock).toHaveText('45:00')
  await focus.getByRole('combobox', { name: '专注时长' }).selectOption('25')
  await focus.getByRole('button', { name: '开始', exact: true }).click()
  await expect(focus.getByRole('combobox', { name: '专注时长' })).toBeDisabled()
  await page.clock.setFixedTime(start + 2 * 60_000)
  await expect(clock).toHaveText('23:00')
  await focus.getByRole('button', { name: '暂停', exact: true }).click()
  await page.clock.setFixedTime(start + 3 * 60_000)
  await page.reload()
  await expect(clock).toHaveText('23:00')
  await expect(focus.getByRole('button', { name: '开始', exact: true })).toBeVisible()
  await focus.getByRole('button', { name: '开始', exact: true }).click()
  await page.clock.setFixedTime(start + 4 * 60_000)
  await page.reload()
  await expect(clock).toHaveText('22:00')
  await expect(focus.getByRole('button', { name: '暂停', exact: true })).toBeVisible()

  const navigation = page.getByRole('navigation', { name: '主导航' })
  await navigation.getByRole('link', { name: '工具', exact: true }).click()
  await page.clock.setFixedTime(start + 5 * 60_000)
  await navigation.getByRole('link', { name: '首页', exact: true }).click()
  await expect(clock).toHaveText('21:00')
  await focus.getByRole('button', { name: '重置', exact: true }).click()
  await expect(clock).toHaveText('25:00')
  await expect(focus.getByRole('button', { name: '开始', exact: true })).toBeVisible()

  await focus.getByRole('button', { name: '开始', exact: true }).click()
  await page.clock.setFixedTime(start)
  await focus.getByRole('button', { name: '暂停', exact: true }).click()
  await page.reload()
  await expect(clock).toHaveText('25:00')
  await expect(focus).not.toContainText('本地数据格式异常')
})

test('后台时间跳跃和离开页面后结束均只完成当前一轮，再手动开始五分钟休息', async ({ page }) => {
  const start = Date.parse('2026-09-05T08:00:00Z')
  await page.clock.setFixedTime(start)
  await openWorkspace(page)
  const focus = page.getByRole('region', { name: '专注计时', exact: true })
  await focus.getByRole('button', { name: '开始', exact: true }).click()
  // Change wall time without ticking through every second, then simulate visibility returning.
  await page.clock.setFixedTime(start + 30 * 60_000)
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')))
  await expect(focus.getByRole('timer')).toHaveText('00:00')
  await expect(focus.getByRole('status')).toHaveText('本轮专注完成，休息一下吧。')
  await focus.getByRole('button', { name: '开始休息', exact: true }).click()
  await expect(focus.getByRole('timer')).toHaveText('05:00')

  const navigation = page.getByRole('navigation', { name: '主导航' })
  await navigation.getByRole('link', { name: '工具', exact: true }).click()
  await page.clock.setFixedTime(start + 40 * 60_000)
  await navigation.getByRole('link', { name: '首页', exact: true }).click()
  await expect(focus.getByRole('timer')).toHaveText('00:00')
  await expect(focus.getByRole('status')).toHaveText('休息结束，准备好再出发。')
  await expect(focus.getByRole('button', { name: '下一轮专注', exact: true })).toBeVisible()
  await page.reload()
  await expect(focus.getByRole('button', { name: '下一轮专注', exact: true })).toBeVisible()
})

test('损坏的待办与计时记录在加载及其他组件保存时不会被覆盖', async ({ page }) => {
  await openWorkspace(page)
  const corruptTodos = '[{"id":"missing-text"}]'
  const corruptTimer = '{"phase":"focus","minutes":25,"remainingMs":0,"deadline":1,"completed":true}'
  await page.evaluate(({ todos, timer }) => {
    localStorage.setItem('devos.workspace.todos', todos)
    localStorage.setItem('devos.workspace.timer', timer)
  }, { todos: corruptTodos, timer: corruptTimer })
  await page.reload()
  await expect(page.getByRole('region', { name: '今日待办', exact: true }).getByRole('status')).toContainText('本地数据格式异常')
  await expect(page.getByRole('region', { name: '专注计时', exact: true }).getByRole('status')).toContainText('本地数据格式异常')
  await page.getByRole('textbox', { name: '临时便笺内容' }).fill('仅更新便笺')
  expect(await page.evaluate(() => ({ todos: localStorage.getItem('devos.workspace.todos'), timer: localStorage.getItem('devos.workspace.timer') }))).toEqual({ todos: corruptTodos, timer: corruptTimer })
  await page.reload()
  await expect(page.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('仅更新便笺')
  expect(await page.evaluate(() => localStorage.getItem('devos.workspace.todos'))).toBe(corruptTodos)
})

test('两个标签页同步待办和便笺，损坏的同步数据不会清空当前内容', async ({ page, context }) => {
  await openWorkspace(page)
  const other = await context.newPage()
  await openWorkspace(other)
  await page.getByRole('textbox', { name: '新增待办' }).fill('标签 A 的任务')
  await page.getByRole('button', { name: '添加待办' }).click()
  await expect(other.getByRole('checkbox', { name: '标签 A 的任务' })).toBeVisible()
  await other.getByRole('textbox', { name: '新增待办' }).fill('标签 B 的任务')
  await other.getByRole('button', { name: '添加待办' }).click()
  await expect(page.getByRole('checkbox', { name: '标签 B 的任务' })).toBeVisible()
  await page.getByRole('textbox', { name: '临时便笺内容' }).fill('两个标签共享的便笺')
  await expect(other.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('两个标签共享的便笺')

  await page.reload()
  await other.reload()
  for (const tab of [page, other]) {
    await expect(tab.locator('.workspace-panel').getByRole('checkbox')).toHaveCount(2)
    await expect(tab.getByRole('checkbox', { name: '标签 A 的任务' })).toBeVisible()
    await expect(tab.getByRole('checkbox', { name: '标签 B 的任务' })).toBeVisible()
    await expect(tab.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('两个标签共享的便笺')
  }
  await other.evaluate(() => localStorage.setItem('devos.workspace.todos', '{broken'))
  await expect(page.getByRole('region', { name: '今日待办', exact: true }).getByRole('status')).toHaveText('另一标签页的数据格式异常，已保留当前内容。')
  await expect(page.locator('.workspace-panel').getByRole('checkbox')).toHaveCount(2)
  expect(await page.evaluate(() => localStorage.getItem('devos.workspace.todos'))).toBe('{broken')
  await other.evaluate(() => localStorage.removeItem('devos.workspace.todos'))
  await expect(page.locator('.workspace-panel').getByRole('checkbox')).toHaveCount(0)
  await expect(page.getByRole('region', { name: '今日待办', exact: true }).getByRole('status')).not.toContainText('格式异常')
  await other.close()
})

test('390px 工作区可完整操作且长任务不会横向溢出', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openWorkspace(page)
  const workspace = page.locator('.workspace-panel')
  await workspace.getByRole('textbox', { name: '新增待办' }).fill('LongUnbrokenTask'.repeat(10))
  await workspace.getByRole('button', { name: '添加待办' }).click()
  await workspace.getByRole('textbox', { name: '临时便笺内容' }).fill('移动端便笺')
  await expect(workspace.getByRole('checkbox')).toBeVisible()
  const widths = await workspace.locator('.workspace-card').evaluateAll(cards => cards.map(card => ({ left: card.getBoundingClientRect().left, right: card.getBoundingClientRect().right, overflow: card.scrollWidth - card.clientWidth })))
  for (const width of widths) {
    expect(width.left).toBeGreaterThanOrEqual(0)
    expect(width.right).toBeLessThanOrEqual(390)
    expect(width.overflow).toBeLessThanOrEqual(1)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('combobox', { name: '选择主题' }).selectOption('light')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  expect(await workspace.evaluate(element => window.getComputedStyle(element).getPropertyValue('--workspace-accent').trim())).toBe(await page.locator('html').evaluate(element => window.getComputedStyle(element).getPropertyValue('--accent').trim()))
})
