import { test, expect } from '@playwright/test'

test('命令面板支持完整键盘导航、滚动、输入法与空结果', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.locator('.tool-card').first()).toBeVisible()
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: '命令面板' })
  const input = dialog.getByRole('combobox', { name: '命令面板搜索' })
  await expect(input).toBeFocused()
  const list = dialog.getByRole('listbox', { name: '搜索结果' })
  await expect(input).toHaveAttribute('aria-controls', await list.getAttribute('id'))
  for (let index = 0; index < 20; index += 1) await input.press('ArrowDown')
  const selected = list.getByRole('option', { selected: true })
  await expect(input).toHaveAttribute('aria-activedescendant', await selected.getAttribute('id'))
  const bounds = await list.boundingBox(), option = await selected.boundingBox()
  expect(option.y).toBeGreaterThanOrEqual(bounds.y - 1)
  expect(option.y + option.height).toBeLessThanOrEqual(bounds.y + bounds.height + 1)
  await input.fill('no-result-for-this-query-98217')
  await expect(list.getByRole('option')).toHaveCount(0)
  await expect(input).not.toHaveAttribute('aria-activedescendant')
  await input.press('Enter')
  await expect(dialog).toBeVisible()
  await input.fill('JSON 格式化')
  await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true, keyCode: 229 })
  await expect(dialog).toBeVisible()
  await input.press('Enter')
  await expect(page).toHaveURL(/#\/tools\/json$/)
  await expect(page.getByRole('heading', { name: 'JSON 格式化' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('recentTools') || '[]'))).toContain('json')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('searchHistory') || '[]'))).toContain('JSON 格式化')
})

test('命令面板搜索 AI 资源并进入筛选结果，关闭后恢复触发器焦点', async ({ page }) => {
  await page.goto('/#/')
  const trigger = page.getByRole('button', { name: '打开命令面板' }).first()
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '命令面板' })
  await dialog.getByRole('button', { name: '关闭命令面板' }).click()
  await expect(trigger).toBeFocused()
  await trigger.click()
  const input = dialog.getByRole('combobox', { name: '命令面板搜索' })
  await input.fill('Local Model')
  await expect(dialog.getByRole('option', { name: /Local Model/ })).toBeVisible()
  await input.press('Enter')
  await expect(page).toHaveURL(/#\/ai\?q=Local%20Model$/)
  await expect(page.getByRole('textbox', { name: '搜索 AI 资源' })).toHaveValue('Local Model')
  await expect(page.getByRole('heading', { name: 'Local Model' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Code Review', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: '搜索 AI 资源' }).fill('Code Review')
  await trigger.click()
  // Fill and submit immediately: reopening must not clear this input in a later effect.
  await input.fill('Local Model')
  await input.press('Enter')
  await expect(page).toHaveURL(/#\/ai\?q=Local%20Model$/)
  await expect(page.getByRole('textbox', { name: '搜索 AI 资源' })).toHaveValue('Local Model')
  await expect(page.getByRole('heading', { name: 'Local Model' })).toBeVisible()
})

test('AI 类型标签可用方向键，卡片复制操作不会误开详情', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/#/ai')
  const all = page.getByRole('tab', { name: '全部', exact: true })
  await all.focus()
  await all.press('ArrowRight')
  const skills = page.getByRole('tab', { name: 'Skills', exact: true })
  await expect(skills).toBeFocused()
  await expect(skills).toHaveAttribute('aria-selected', 'true')
  await skills.press('End')
  const products = page.getByRole('tab', { name: '应用 / 产品', exact: true })
  await expect(products).toBeFocused()
  await expect(products).toHaveAttribute('aria-selected', 'true')
  await products.press('Home')
  await expect(all).toBeFocused()
  const review = page.locator('.ai-resource-card', { has: page.getByRole('heading', { name: 'Code Review', exact: true }) })
  await review.getByRole('button', { name: '复制安装方式', exact: true }).press('Enter')
  await expect(review.getByRole('button', { name: '已复制', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('Prioritize bugs')
  await review.focus()
  await review.press('Enter')
  await expect(page.getByRole('dialog', { name: 'Code Review' })).toBeVisible()
})
