import { test, expect } from '@playwright/test'

test.use({ reducedMotion: 'reduce' })

test('新访客默认浏览资源，个人模式记住偏好且切回资源时保留数据', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.getByTestId('boot-layer')).toBeHidden()
  const resources = page.getByRole('button', { name: '资源浏览', exact: true })
  const personal = page.getByRole('button', { name: '我的工作区', exact: true })
  const workspace = page.locator('.workspace-panel')
  await expect(resources).toBeVisible()
  await expect(personal).toBeVisible()
  await expect(workspace).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '今日待办', exact: true })).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: '临时便笺内容' })).toHaveCount(0)

  await personal.click()
  await expect(workspace).toBeVisible()
  await expect(workspace.getByRole('checkbox')).toHaveCount(0)
  await workspace.getByRole('textbox', { name: '新增待办' }).fill('保留我的个人任务')
  await workspace.getByRole('button', { name: '添加待办' }).click()
  await workspace.getByRole('textbox', { name: '临时便笺内容' }).fill('切换浏览模式后也要保留的灵感')
  expect(await page.evaluate(() => localStorage.getItem('devos-home-view'))).toBe('personal')

  await page.reload()
  await expect(workspace.getByRole('checkbox', { name: '保留我的个人任务' })).toBeVisible()
  await expect(workspace.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('切换浏览模式后也要保留的灵感')
  await resources.click()
  await expect(workspace).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: '临时便笺内容' })).toHaveCount(0)
  await page.reload()
  await expect(workspace).toHaveCount(0)
  await personal.click()
  await expect(workspace.getByRole('checkbox', { name: '保留我的个人任务' })).toBeVisible()
  await expect(workspace.getByRole('textbox', { name: '临时便笺内容' })).toHaveValue('切换浏览模式后也要保留的灵感')
})

test('首次访问可直达示例工具，手机切换工作区后直接输入', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/')
  const start = page.getByRole('link', { name: '试用 JSON 工具', exact: true })
  await expect(start).toBeInViewport()
  await start.click()
  await expect(page.getByLabel('JSON 输入')).toHaveValue('{"hello":"world"}')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByLabel('结果')).toHaveValue('{\n  "hello": "world"\n}')
  await page.goto('/#/')
  await page.getByRole('button', { name: '我的工作区', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '新增待办', exact: true })).toBeFocused()
  await expect(page.getByRole('textbox', { name: '新增待办', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: '资源浏览', exact: true }).click()
  await page.route('**/tools-manifests.json', async route => {
    const response = await route.fetch()
    const tools = await response.json()
    await route.fulfill({ response, json: tools.map(tool => tool.id === 'json' ? { ...tool, enabled: false } : tool) })
  })
  await page.reload()
  await expect(start).toHaveCount(0)
  await expect(page.getByRole('link', { name: '探索工具箱', exact: true })).toHaveAttribute('href', '#/tools')
})
