import { test, expect } from '@playwright/test'

test.use({ reducedMotion: 'reduce', viewport: { width: 390, height: 844 } })
test.beforeEach(async ({ context }) => {
  await context.addInitScript(() => sessionStorage.setItem('devos-boot', '1'))
})

test('章节导航把键盘焦点带到内容，下一次 Tab 可直接操作该章节', async ({ page }) => {
  await page.goto('/#/')
  const chapter = page.getByRole('navigation', { name: '章节目录' }).getByRole('link', { name: '03 网站', exact: true })
  await chapter.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#sites')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('#sites').getByRole('link', { name: '全部站点 ↗' })).toBeFocused()
})

test('开启工作区后直接输入，删除长待办可撤销且键盘焦点不会丢失', async ({ page }) => {
  await page.goto('/#/')
  await page.getByRole('button', { name: '开启我的工作区', exact: true }).click()
  const input = page.getByRole('textbox', { name: '新增待办', exact: true })
  await expect(input).toBeFocused()
  await expect(input).toBeInViewport()
  const text = 'LongUnbrokenTask'.repeat(10)
  await input.fill(text)
  await page.keyboard.press('Enter')
  await expect(input).toHaveValue('')
  await expect(input).toBeFocused()
  await page.getByRole('checkbox', { name: text }).check()
  const remove = page.getByRole('button', { name: `删除待办：${text}`, exact: true })
  await remove.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('checkbox', { name: text })).toHaveCount(0)
  await expect(input).toBeFocused()
  const undo = page.getByRole('button', { name: '撤销删除', exact: true })
  await expect(undo).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await undo.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('checkbox', { name: text })).toBeChecked()
  await expect(input).toBeFocused()
  await expect(undo).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('checkbox', { name: text })).toBeChecked()
})
