const $ = s => document.querySelector(s)
let state = { navigation: [], categories: [], site: {} }
const request = async (path, options) => { const r = await fetch(`/api/${path}`, { headers: { 'content-type': 'application/json' }, ...options }); const data = await r.json(); if (!r.ok) throw Error(data.error || '请求失败'); return data }
const status = message => $('#status').textContent = message
function input(name, value, label) { return `<label>${label || name}<input name="${name}" value="${value ?? ''}" required></label>` }
function renderSite() { $('#site').innerHTML = `${input('name', state.site.name, '站点名称')}${input('title', state.site.title, '标题')}${input('description', state.site.description, '描述')}${input('github', state.site.github, 'GitHub')}${input('footer', state.site.footer, 'Footer')}${input('logo', state.site.logo, 'Logo')}<button>保存配置</button>` }
function render() { renderSite(); $('#categories').innerHTML = state.categories.sort((a,b)=>a.order-b.order).map(c=>`<div class="row"><strong>${c.name}</strong><small>${c.id} · ${c.icon} · order ${c.order}</small><span><button data-edit-category="${c.id}">编辑</button> <button class="danger" data-delete-category="${c.id}">删除</button></span></div>`).join(''); $('#navigation').innerHTML = state.navigation.sort((a,b)=>a.order-b.order).map(n=>`<div class="row"><strong>${n.name} ${n.enabled?'':'（禁用）'}</strong><small>${n.url} · ${n.category} · ${n.icon}</small><span><button data-edit="${n.id}">编辑</button> <button data-toggle="${n.id}">${n.enabled?'禁用':'启用'}</button> <button class="danger" data-delete="${n.id}">删除</button></span></div>`).join('') }
async function reload(message='已更新') { [state.navigation, state.categories, state.site] = await Promise.all([request('navigation'), request('categories'), request('site')]); render(); status(message) }
$('#site').addEventListener('submit', async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); try { await request('site', { method:'PUT', body:JSON.stringify(data) }); await reload('站点配置已保存') } catch (e) { status(e.message) } })
$('#category-form').addEventListener('submit', async e => { e.preventDefault(); const f=new FormData(e.target); const data=Object.fromEntries(f); const originalId=data.originalId; delete data.originalId; data.order=Number(data.order); try { await request(originalId ? `categories/${originalId}` : 'categories', { method:originalId?'PUT':'POST', body:JSON.stringify(data) }); e.target.reset(); e.target.querySelector('button').textContent='新增分类'; await reload(originalId?'分类已保存':'分类已新增') } catch (e) { status(e.message) } })
$('#nav-form').addEventListener('submit', async e => { e.preventDefault(); const f=new FormData(e.target); const data=Object.fromEntries(f); const originalId=data.originalId; delete data.originalId; data.tags=data.tags.split(',').map(x=>x.trim()).filter(Boolean); data.order=Number(data.order); data.enabled=f.has('enabled'); try { await request(originalId ? `navigation/${originalId}` : 'navigation', { method:originalId?'PUT':'POST', body:JSON.stringify(data) }); e.target.reset(); e.target.querySelector('button').textContent='新增网址'; await reload(originalId?'网址已保存':'网址已新增') } catch (e) { status(e.message) } })
function fill(form, item, tags = false) { for (const [key, value] of Object.entries(item)) { const field=form.elements[key]; if (!field) continue; if (field.type === 'checkbox') field.checked=Boolean(value); else field.value=tags && Array.isArray(value) ? value.join(', ') : value } form.elements.originalId.value=item.id; form.querySelector('button').textContent='保存修改'; form.scrollIntoView({ behavior:'smooth', block:'center' }) }
document.addEventListener('click', async e => { const el=e.target.closest('button'); if (!el) return; try { if (el.dataset.edit) fill($('#nav-form'), state.navigation.find(x=>x.id===el.dataset.edit), true); if (el.dataset.editCategory) fill($('#category-form'), state.categories.find(x=>x.id===el.dataset.editCategory)); if (el.dataset.delete) { await request(`navigation/${el.dataset.delete}`, {method:'DELETE'}); await reload('网址已删除') } if (el.dataset.toggle) { const item=state.navigation.find(x=>x.id===el.dataset.toggle); await request(`navigation/${item.id}`, {method:'PUT',body:JSON.stringify({enabled:!item.enabled})}); await reload('状态已更新') } if (el.dataset.deleteCategory) { await request(`categories/${el.dataset.deleteCategory}`, {method:'DELETE'}); await reload('分类已删除') } } catch (e) { status(e.message) } })
reload().catch(e => status(e.message))
